### ISSUE TITLE
updateConfiguration on collectionSpecificSearchParameters is not triggering a search request

### ISSUE THREAD

**Issue by JZubero** [typesense/typesense-instantsearch-adapter#124]
Knowing that the method `updateConfiguration` is only available as a preview in `2.4.2-1`, updating a config option on any collection within `collectionSpecificSearchParameters`, e.g. `hidden_hits`, does not seem to trigger a subsequent call to the service. Hence, the search client does not receive new results.

**Comment by jasonbosco** [comment]
As far as I can tell, `updateConfiguration()` does not cause Instantsearch to trigger a search. All it does is update the internal configuration of the adapter, so that the next search that is done uses the new configuration. 

So you'd probably need to refresh the Instantsearch widgets using some mechanism Instantsearch provides to get it to to trigger a new search.

**Comment by JZubero** [comment]
OK, I'll give it a try. Thanks!
