### ISSUE TITLE
Can I use it with react-instantsearch-hooks for react native project?

### ISSUE THREAD

**Issue by sudipbhujel** [typesense/typesense-instantsearch-adapter#128]
I want to use typesense in react-native project and want to use instant search also, I didn't find any documentation about these stuff. I wonder if it is possible to use this adapter with react instant search hooks.🤔

**Comment by jasonbosco** [comment]
I’ve heard at least one user who used react-instantsearch with react native and this adapter. So I’d imagine the hooks version also works with react native. But let me know if you run into any issues.

**Comment by zergormagn** [comment]
I setup a codebox with the latest hooks library and TS adapter.   There are a few problems still, largest ones being:
1) Issue with hits display
2) DynamicWidgets still not supported by TS adapter
I hardcoded a "brands" widget to sidestep the 2nd issue.  And it does work somewhat, although codesandbox seems to have stability issues running it at times, maybe some conflicts in the adapter? 

https://codesandbox.io/s/7pejpz?file=/pages/index.tsx
original very nice barebones example:
https://codesandbox.io/s/late-frost-bim3tb?file=/pages/index.tsx

I think having such sandboxes available from TS would be a great starting point for many.

**Comment by jasonbosco** [comment]
Typesense doesn't support `DynamicWidgets` yet, even outside of react-instantsearch-hooks, since we need to add support for it on the Typesense Server side first: https://github.com/typesense/typesense-instantsearch-adapter/issues/106#issuecomment-1285938440

May I know what you mean by "Issue with hits"? Do you see an error? I'm not able to access that codesandbox since I don't have access to the Typesense cluster you're using...

**Comment by zergormagn** [comment]
That TS server is behind cloudflare and my guess is that cloudflare banned codesandbox access because TS adapter kept trying to reconnect without an error that codesandbox understands, so codesandbox also got into a loop trying to recreate the sandbox...

The Hits issue is more to do with react native type restructuring not TS.   I have a new Hooks version setup here (with all modules updated to latest). Sometimes one needs to remove the dynamicwidgets tag for anything to show up when using TSadapter. Other times it loads with it left in the code.   Strange as there is no error visible either way.

https://codesandbox.io/s/objective-architecture-orsp5x?file=/pages/index.tsx

**Comment by EL-MEHDI-ESSAADI** [comment]
> I’ve heard at least one user who used react-instantsearch with react native and this adapter. So I’d imagine the hooks version also works with react native. But let me know if you run into any issues.

Yes it works with me too, I used typesense-instantsearch-adapter with react-instantsearch-core for hooks.
Docs for how to use React InstantSearch with React Native [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/) just make sure to use typesense-instantsearch-adapter instead of algoliasearch/lite package for initializing searchClient
