### ISSUE TITLE
Supporting wildcard facets like in Algolia

### ISSUE THREAD

**Issue by shasha79** [typesense/typesense-instantsearch-adapter#129]
## Description

I am trying to migrate InstantSearch-based site from Algolia to Typesense and facing the issue. Algolia supports getting all available facets by using a wildcard:  facets:['*'] (https://www.algolia.com/doc/api-reference/api-parameters/facets/). Typense returns error in this case:
_Could not find a facet field named `*` in the schema._
Any idea how to work around it?

## Metadata

**Typsense Version**:

**OS**:

**Comment by jasonbosco** [comment]
@shasha79 Typesense doesn't yet support `facet_by: *`, so each facet field should be explicitly listed in the query. See #106. 

On a side note, may I know which instantsearch widget this is for?

**Comment by shasha79** [comment]
I am migrating the whole Algolia template, there are many widgets there
https://github.com/algolia/pwa-ecom-ui-template

**Comment by zergormagn** [comment]
Dynamicwidgets with facets:[] also fails.  I tried switching the search client between a compiled Algolia version using dynamicwidgets with facets:[] to a TS server, I actually got the TS instantsearch adapter requesting unlisted facets from the TS server.  
I'm guessing the  Instantsearch client must have cached some initial facet request and once it was directed at the TS adapter it still worked for the TS server.   I don't know if dynamicwidgets could render, because one of the fields in Algolia sample data was not on the TS server so the adapter tripped over it.

**Comment by jasonbosco** [comment]
Related to #106

**Comment by pixelkoduje** [comment]
I see that instead of the `"*" error`, it shows the error 'Field `name` is not marked as a guy in the schema.'
I using `const data = useDynamicWidgets({
     guys: ['*']
   })` in docker version 0.25.0.rc9
It's not finished, do I need to do something else to make it work?
I'm using react-instantsearch-hooks-web

**Comment by jasonbosco** [comment]
This is now supported: https://github.com/typesense/typesense-instantsearch-adapter/issues/150#issuecomment-1441201147
