### ISSUE TITLE
configurerelateditems from instantsearch working with typesense?

### ISSUE THREAD

**Issue by pixelkoduje** [typesense/typesense-instantsearch-adapter#146]
## Description
Is working in typesense? I can't run it.
https://instantsearchjs.netlify.app/stories/js/?path=/story/basics-configurerelateditems--default

## Expected Behavior
![image](https://user-images.githubusercontent.com/102321542/218334934-3c237e2b-c1af-4d7f-83d4-dcf8b1edb4d3.png)

**Comment by pixelkoduje** [comment]
I tested further, I don't think it works. I get an error:
`Error: 404 - Could not find a filter field named `objectID` in the schema.`

My setting component.
![image](https://user-images.githubusercontent.com/102321542/218343015-7198ba69-a5a7-466b-9cf0-8145c6982bfc.png)

data.hit - this is data from the component that was clicked (To open a list of similar products for viewing when clicked). Unfortunately it does not work. And in the typesense list it says that this function is working.

**Comment by pixelkoduje** [comment]
I'd appreciate a minimal (small example) of how to do it right, if it works. Thanks

**Comment by jasonbosco** [comment]
@pixelkoduje The related widgets item does not work with Typesense (yet), since Typesense has a different way to fetch related items using vector search. 

Here's an example of how to do this with Typesense: 

1. Visit https://ecommerce-store.typesense.org/
2. Click on "Find Similar" under any product
3. You'll see notes on how to implement it with Typesense
