### ISSUE TITLE
angular-instantsearch deprecation

### ISSUE THREAD

**Issue by Jad31** [typesense/typesense-instantsearch-adapter#209]
I am currently using `typesense-instantsearch-adapter` for implementing instant search in an Angular application. However, I have noticed that `angular-instantsearch` is being deprecated, as mentioned in their repository
![image](https://github.com/typesense/typesense-instantsearch-adapter/assets/46532649/6b306885-d02c-48eb-affe-c226d195a6e3)

Given this deprecation, I am concerned about the future compatibility and support for Angular applications.

Are there any plans or ongoing discussions to support Angular in light of the deprecation of `angular-instantsearch`? If so, could you please provide some insights or a roadmap? Additionally, are there any recommended alternatives or migration paths for implementing `typesense-instantsearch` in newer versions of Angular (v16 and beyond)?

**Comment by jasonbosco** [comment]
The typesense-instantsearch-adapter (this repo) only transforms queries generated by any of the instantsearch libraries into a format that Typesense understands and vice-versa with the response from Typesense. So the adapter itself is agnostic to which FE framework you're using. 

We do not have any plans to maintain the upstream angular-instantsearch project once Algolia deprecates it, since it sounds like a non-trivial amount of effort based on this blog post: https://www.algolia.com/blog/algolia/migrating-from-angular-instantsearch/

In that same link, Algolia recommends migrating to using Instantsearch.js within Angular applications going forward. So you should still be able to use these UI components inside an Angular application.
